//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIusuario.ServicioUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioModels", Namespace="http://schemas.datacontract.org/2004/07/UsuarioWCF.Models")]
    [System.SerializableAttribute()]
    public partial class UsuarioModels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuario.IUsuarios")]
    public interface IUsuarios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetAllUsuarioNombre", ReplyAction="http://tempuri.org/IUsuarios/GetAllUsuarioNombreResponse")]
        UIusuario.ServicioUsuario.UsuarioModels GetAllUsuarioNombre(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetAllUsuarioNombre", ReplyAction="http://tempuri.org/IUsuarios/GetAllUsuarioNombreResponse")]
        System.Threading.Tasks.Task<UIusuario.ServicioUsuario.UsuarioModels> GetAllUsuarioNombreAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/AddUsuario", ReplyAction="http://tempuri.org/IUsuarios/AddUsuarioResponse")]
        string AddUsuario(UIusuario.ServicioUsuario.UsuarioModels company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/AddUsuario", ReplyAction="http://tempuri.org/IUsuarios/AddUsuarioResponse")]
        System.Threading.Tasks.Task<string> AddUsuarioAsync(UIusuario.ServicioUsuario.UsuarioModels company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/UpUsuario", ReplyAction="http://tempuri.org/IUsuarios/UpUsuarioResponse")]
        void UpUsuario(UIusuario.ServicioUsuario.UsuarioModels company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/UpUsuario", ReplyAction="http://tempuri.org/IUsuarios/UpUsuarioResponse")]
        System.Threading.Tasks.Task UpUsuarioAsync(UIusuario.ServicioUsuario.UsuarioModels company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/DeleteUsuario", ReplyAction="http://tempuri.org/IUsuarios/DeleteUsuarioResponse")]
        void DeleteUsuario(UIusuario.ServicioUsuario.UsuarioModels company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/DeleteUsuario", ReplyAction="http://tempuri.org/IUsuarios/DeleteUsuarioResponse")]
        System.Threading.Tasks.Task DeleteUsuarioAsync(UIusuario.ServicioUsuario.UsuarioModels company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetAllUsuario", ReplyAction="http://tempuri.org/IUsuarios/GetAllUsuarioResponse")]
        UIusuario.ServicioUsuario.UsuarioModels[] GetAllUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarios/GetAllUsuario", ReplyAction="http://tempuri.org/IUsuarios/GetAllUsuarioResponse")]
        System.Threading.Tasks.Task<UIusuario.ServicioUsuario.UsuarioModels[]> GetAllUsuarioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuariosChannel : UIusuario.ServicioUsuario.IUsuarios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosClient : System.ServiceModel.ClientBase<UIusuario.ServicioUsuario.IUsuarios>, UIusuario.ServicioUsuario.IUsuarios {
        
        public UsuariosClient() {
        }
        
        public UsuariosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UIusuario.ServicioUsuario.UsuarioModels GetAllUsuarioNombre(string Nombre) {
            return base.Channel.GetAllUsuarioNombre(Nombre);
        }
        
        public System.Threading.Tasks.Task<UIusuario.ServicioUsuario.UsuarioModels> GetAllUsuarioNombreAsync(string Nombre) {
            return base.Channel.GetAllUsuarioNombreAsync(Nombre);
        }
        
        public string AddUsuario(UIusuario.ServicioUsuario.UsuarioModels company) {
            return base.Channel.AddUsuario(company);
        }
        
        public System.Threading.Tasks.Task<string> AddUsuarioAsync(UIusuario.ServicioUsuario.UsuarioModels company) {
            return base.Channel.AddUsuarioAsync(company);
        }
        
        public void UpUsuario(UIusuario.ServicioUsuario.UsuarioModels company) {
            base.Channel.UpUsuario(company);
        }
        
        public System.Threading.Tasks.Task UpUsuarioAsync(UIusuario.ServicioUsuario.UsuarioModels company) {
            return base.Channel.UpUsuarioAsync(company);
        }
        
        public void DeleteUsuario(UIusuario.ServicioUsuario.UsuarioModels company) {
            base.Channel.DeleteUsuario(company);
        }
        
        public System.Threading.Tasks.Task DeleteUsuarioAsync(UIusuario.ServicioUsuario.UsuarioModels company) {
            return base.Channel.DeleteUsuarioAsync(company);
        }
        
        public UIusuario.ServicioUsuario.UsuarioModels[] GetAllUsuario() {
            return base.Channel.GetAllUsuario();
        }
        
        public System.Threading.Tasks.Task<UIusuario.ServicioUsuario.UsuarioModels[]> GetAllUsuarioAsync() {
            return base.Channel.GetAllUsuarioAsync();
        }
    }
}
